import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import { format } from "date-fns";

// Server function to fetch sequence by ID
const fetchSequenceFn = createServerFn({ method: "GET" })
  .validator((input: unknown) => ({ id: (input as any)?.id as string }))
  .handler(async ({ data }) => {
    const supabase = createClient(
      process.env.VITE_SUPABASE_URL ?? import.meta.env.VITE_SUPABASE_URL,
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
    );
    const { data: seq, error } = await supabase
      .from("bde_sequences")
      .select("*")
      .eq("id", data.id)
      .single();
    if (error || !seq) return null;
    return seq as {
      id: string;
      created_at: string;
      generated_by: string;
      generated_by_email: string;
      client_name: string;
      linkedin_post: string;
      full_sequence: string;
    };
  });

export const Route = createFileRoute("/outreach/$id")({
  loader: async ({ params }) => {
    const seq = await fetchSequenceFn({ data: { id: params.id } });
    return { seq };
  },
  component: OutreachPage,
});

function OutreachPage() {
  const { seq } = Route.useLoaderData();

  if (!seq) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "#0f0f0f", color: "#fff", fontFamily: "Inter, sans-serif" }}>
        <div style={{ textAlign: "center" }}>
          <div style={{ fontSize: 48, marginBottom: 16 }}>🔍</div>
          <h2 style={{ color: "#888", fontWeight: 400 }}>Sequence not found</h2>
          <p style={{ color: "#555" }}>This link may have expired or is invalid.</p>
        </div>
      </div>
    );
  }

  const createdDate = format(new Date(seq.created_at), "dd MMM yyyy, hh:mm a");

  // Parse sequence into sections for better rendering
  const sections = parseSequence(seq.full_sequence);

  return (
    <div style={{ minHeight: "100vh", background: "#0a0a0a", fontFamily: "'Inter', -apple-system, sans-serif", color: "#e8e8e8" }}>
      {/* Header */}
      <div style={{ background: "linear-gradient(135deg, #1a1008 0%, #2a1a04 100%)", borderBottom: "1px solid #3a2a10", padding: "24px 32px" }}>
        <div style={{ maxWidth: 900, margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}>
            <div style={{ width: 36, height: 36, borderRadius: 8, background: "linear-gradient(135deg, #c9a227, #f0c040)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18 }}>⚡</div>
            <span style={{ color: "#c9a227", fontWeight: 700, fontSize: 14, letterSpacing: 2, textTransform: "uppercase" }}>Colladome BDE Outreach</span>
          </div>
          <h1 style={{ fontSize: 28, fontWeight: 700, margin: "0 0 8px", color: "#fff" }}>
            {seq.client_name && seq.client_name !== "Unknown" ? `Outreach: ${seq.client_name}` : "Outreach Sequence"}
          </h1>
          <div style={{ display: "flex", gap: 24, flexWrap: "wrap" }}>
            <MetaBadge icon="👤" label="Generated by" value={seq.generated_by} />
            <MetaBadge icon="📅" label="Created" value={createdDate} />
            {seq.client_name && seq.client_name !== "Unknown" && (
              <MetaBadge icon="🏢" label="Client" value={seq.client_name} />
            )}
          </div>
        </div>
      </div>

      <div style={{ maxWidth: 900, margin: "0 auto", padding: "32px 32px" }}>
        {/* LinkedIn Post (original) */}
        {seq.linkedin_post && (
          <div style={{ background: "#141414", border: "1px solid #2a2a2a", borderRadius: 12, padding: "20px 24px", marginBottom: 32 }}>
            <div style={{ color: "#888", fontSize: 11, fontWeight: 600, letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 10 }}>Original Requirement / LinkedIn Post</div>
            <p style={{ color: "#aaa", lineHeight: 1.7, margin: 0, fontSize: 14, whiteSpace: "pre-wrap" }}>{seq.linkedin_post}</p>
          </div>
        )}

        {/* Day sections */}
        {sections.map((section, i) => (
          <DaySection key={i} section={section} />
        ))}

        {/* Raw fallback if parsing fails */}
        {sections.length === 0 && (
          <div style={{ background: "#141414", border: "1px solid #2a2a2a", borderRadius: 12, padding: "24px", whiteSpace: "pre-wrap", lineHeight: 1.8, fontSize: 14, color: "#ccc" }}>
            {seq.full_sequence}
          </div>
        )}

        {/* Footer */}
        <div style={{ textAlign: "center", marginTop: 48, padding: "24px", borderTop: "1px solid #1e1e1e", color: "#444", fontSize: 12 }}>
          Generated by Pulse Assistant • Colladome Internal Tool • {createdDate}
        </div>
      </div>
    </div>
  );
}

function MetaBadge({ icon, label, value }: { icon: string; label: string; value: string }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
      <span style={{ fontSize: 13 }}>{icon}</span>
      <span style={{ color: "#555", fontSize: 12 }}>{label}:</span>
      <span style={{ color: "#bbb", fontSize: 12, fontWeight: 600 }}>{value}</span>
    </div>
  );
}

interface Section {
  title: string;
  content: string;
  isDay?: boolean;
  dayNumber?: number;
}

function parseSequence(text: string): Section[] {
  const sections: Section[] = [];
  // Split by DAY headers
  const dayPattern = /(?:^|\n)(DAY\s+\d+|Day\s+\d+|---\s*\n\s*DAY\s+\d+)/gm;
  const parts = text.split(/\n(?=DAY\s+\d|Day\s+\d)/i);

  // First part might be analysis
  if (parts[0] && !parts[0].match(/^DAY\s+\d/i)) {
    sections.push({ title: "Lead Analysis & Projects Selected", content: parts[0].trim(), isDay: false });
  }

  for (const part of parts.slice(parts[0]?.match(/^DAY\s+\d/i) ? 0 : 1)) {
    const match = part.match(/^(DAY\s+\d+)/i);
    if (match) {
      const dayNum = parseInt(part.match(/\d+/)?.[0] ?? "0");
      sections.push({ title: match[1].toUpperCase(), content: part.replace(match[1], "").trim(), isDay: true, dayNumber: dayNum });
    }
  }

  return sections;
}

function DaySection({ section }: { section: Section }) {
  const dayColors: Record<number, string> = {
    0: "#c9a227", 1: "#4a9eff", 2: "#22c55e", 3: "#f59e0b",
    4: "#ef4444", 5: "#8b5cf6", 6: "#ec4899",
  };
  const color = section.dayNumber !== undefined ? (dayColors[section.dayNumber] ?? "#888") : "#c9a227";

  const messages = parseMessages(section.content);

  return (
    <div style={{ marginBottom: 24, background: "#111", border: `1px solid #222`, borderLeft: `3px solid ${color}`, borderRadius: 12, overflow: "hidden" }}>
      <div style={{ background: "#161616", padding: "14px 20px", borderBottom: "1px solid #1e1e1e", display: "flex", alignItems: "center", gap: 10 }}>
        {section.isDay && (
          <span style={{ background: color + "22", color: color, fontSize: 11, fontWeight: 700, padding: "2px 10px", borderRadius: 20, letterSpacing: 1 }}>
            {section.title}
          </span>
        )}
        {!section.isDay && (
          <span style={{ color: "#888", fontSize: 12, fontWeight: 600, letterSpacing: 1, textTransform: "uppercase" }}>{section.title}</span>
        )}
      </div>
      <div style={{ padding: "16px 20px" }}>
        {messages.length > 0 ? (
          messages.map((msg, i) => <MessageBlock key={i} msg={msg} />)
        ) : (
          <pre style={{ color: "#aaa", fontSize: 13, lineHeight: 1.8, margin: 0, whiteSpace: "pre-wrap", fontFamily: "inherit" }}>{section.content}</pre>
        )}
      </div>
    </div>
  );
}

interface MessageBlock {
  channel: string;
  subject?: string;
  body: string;
  charCount?: number;
}

function parseMessages(text: string): MessageBlock[] {
  const blocks: MessageBlock[] = [];
  const channelPatterns = [
    { label: "📧 Email", pattern: /Email(?:\s+Body)?:\s*\n([\s\S]+?)(?=\n(?:WhatsApp|LinkedIn|Call Script|Phone Call|---|\n\n[A-Z])|\n*$)/i },
    { label: "💬 WhatsApp", pattern: /WhatsApp(?:\s+(?:Message|Follow-up|Final))?:\s*\n([\s\S]+?)(?=\n(?:Email|LinkedIn|Call Script|Phone Call|---|\n\n[A-Z])|\n*$)/i },
    { label: "💼 LinkedIn", pattern: /LinkedIn(?:\s+(?:Connection Request|Follow-up|DM))?:\s*\n([\s\S]+?)(?=\n(?:Email|WhatsApp|Call Script|Phone Call|---|\n\n[A-Z])|\n*$)/i },
    { label: "📞 Call Script", pattern: /(?:Call Script|Phone Call Script):\s*\n([\s\S]+?)(?=\n(?:Email|WhatsApp|LinkedIn|---|\n\n[A-Z])|\n*$)/i },
  ];

  const subjectMatch = text.match(/Email Subject:\s*(.+)/i);
  const subject = subjectMatch?.[1]?.trim();

  for (const { label, pattern } of channelPatterns) {
    const match = text.match(pattern);
    if (match) {
      const body = match[1].trim();
      blocks.push({
        channel: label,
        subject: label.includes("Email") ? subject : undefined,
        body,
        charCount: label.includes("LinkedIn") ? body.length : undefined,
      });
    }
  }
  return blocks;
}

function MessageBlock({ msg }: { msg: MessageBlock }) {
  const channelColors: Record<string, { bg: string; border: string; label: string }> = {
    "📧 Email": { bg: "#0d1117", border: "#1e3a5f", label: "#4a9eff" },
    "💬 WhatsApp": { bg: "#0d1a0d", border: "#1a4a1a", label: "#22c55e" },
    "💼 LinkedIn": { bg: "#0d1020", border: "#1e2a5f", label: "#6875f5" },
    "📞 Call Script": { bg: "#1a0d0d", border: "#5f1e1e", label: "#ef4444" },
  };
  const style = channelColors[msg.channel] ?? { bg: "#111", border: "#333", label: "#888" };
  const isLinkedIn = msg.channel.includes("LinkedIn");
  const charCount = msg.body.length;
  const overLimit = isLinkedIn && charCount > 300;

  return (
    <div style={{ background: style.bg, border: `1px solid ${style.border}`, borderRadius: 8, padding: "14px 16px", marginBottom: 12 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
        <span style={{ color: style.label, fontSize: 11, fontWeight: 700, letterSpacing: 0.5 }}>{msg.channel}</span>
        {isLinkedIn && (
          <span style={{ fontSize: 10, color: overLimit ? "#ef4444" : "#22c55e", background: overLimit ? "#2a0a0a" : "#0a2a0a", padding: "2px 8px", borderRadius: 10 }}>
            {charCount}/300 chars {overLimit ? "⚠️ OVER LIMIT" : "✓"}
          </span>
        )}
      </div>
      {msg.subject && (
        <div style={{ color: "#888", fontSize: 11, marginBottom: 6 }}>
          <span style={{ color: "#555" }}>Subject: </span>
          <span style={{ color: "#ccc", fontWeight: 600 }}>{msg.subject}</span>
        </div>
      )}
      <p style={{ color: "#d4d4d4", fontSize: 13, lineHeight: 1.8, margin: 0, whiteSpace: "pre-wrap" }}>{msg.body}</p>
      <div style={{ marginTop: 8, display: "flex", gap: 8 }}>
        <CopyButton text={msg.subject ? `Subject: ${msg.subject}\n\n${msg.body}` : msg.body} />
      </div>
    </div>
  );
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = React.useState(false);

  const copy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button onClick={copy} style={{ background: copied ? "#22c55e22" : "#1e1e1e", border: `1px solid ${copied ? "#22c55e" : "#333"}`, color: copied ? "#22c55e" : "#666", fontSize: 11, padding: "4px 12px", borderRadius: 6, cursor: "pointer", transition: "all 0.2s" }}>
      {copied ? "✓ Copied!" : "Copy"}
    </button>
  );
}

import React from "react";
