/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedPunchRouteImport } from './routes/_authenticated/punch'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAccessRouteImport } from './routes/_authenticated/access'

const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPunchRoute = AuthenticatedPunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/access': typeof AuthenticatedAccessRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/punch': typeof AuthenticatedPunchRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/access': typeof AuthenticatedAccessRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/punch': typeof AuthenticatedPunchRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/_authenticated/access': typeof AuthenticatedAccessRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/punch': typeof AuthenticatedPunchRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/access'
    | '/calendar'
    | '/dashboard'
    | '/finances'
    | '/leave'
    | '/projects'
    | '/punch'
    | '/resources'
    | '/tasks'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/access'
    | '/calendar'
    | '/dashboard'
    | '/finances'
    | '/leave'
    | '/projects'
    | '/punch'
    | '/resources'
    | '/tasks'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/_authenticated/access'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/finances'
    | '/_authenticated/leave'
    | '/_authenticated/projects'
    | '/_authenticated/punch'
    | '/_authenticated/resources'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/punch': {
      id: '/_authenticated/punch'
      path: '/punch'
      fullPath: '/punch'
      preLoaderRoute: typeof AuthenticatedPunchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access': {
      id: '/_authenticated/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthenticatedAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPunchRoute: typeof AuthenticatedPunchRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPunchRoute: AuthenticatedPunchRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
