/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoogleCalendarConnectRouteImport } from './routes/google-calendar-connect'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedTimesheetRouteImport } from './routes/_authenticated/timesheet'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedPunchRouteImport } from './routes/_authenticated/punch'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProjectBurnRouteImport } from './routes/_authenticated/project-burn'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedOnboardingPendingRouteImport } from './routes/_authenticated/onboarding-pending'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMyTimesheetRouteImport } from './routes/_authenticated/my-timesheet'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompleteOnboardingRouteImport } from './routes/_authenticated/complete-onboarding'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBdRouteImport } from './routes/_authenticated/bd'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAccessRouteImport } from './routes/_authenticated/access'
import { Route as AuthenticatedBdIndexRouteImport } from './routes/_authenticated/bd.index'
import { Route as ApiAssistantTranscribeRouteImport } from './routes/api/assistant/transcribe'
import { Route as ApiAssistantChatRouteImport } from './routes/api/assistant/chat'
import { Route as AuthenticatedHrOnboardingRouteImport } from './routes/_authenticated/hr.onboarding'
import { Route as AuthenticatedHrLeaveRouteImport } from './routes/_authenticated/hr.leave'
import { Route as AuthenticatedBoardDeptRouteImport } from './routes/_authenticated/board.$dept'
import { Route as AuthenticatedBdTeamRouteImport } from './routes/_authenticated/bd.team'
import { Route as AuthenticatedBdReportsRouteImport } from './routes/_authenticated/bd.reports'
import { Route as AuthenticatedBdRecurringRouteImport } from './routes/_authenticated/bd.recurring'
import { Route as AuthenticatedBdActivityTypesRouteImport } from './routes/_authenticated/bd.activity-types'
import { Route as AuthenticatedAdminTaxonomyRouteImport } from './routes/_authenticated/admin.taxonomy'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'

const GoogleCalendarConnectRoute = GoogleCalendarConnectRouteImport.update({
  id: '/google-calendar-connect',
  path: '/google-calendar-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimesheetRoute = AuthenticatedTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPunchRoute = AuthenticatedPunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectBurnRoute =
  AuthenticatedProjectBurnRouteImport.update({
    id: '/project-burn',
    path: '/project-burn',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingPendingRoute =
  AuthenticatedOnboardingPendingRouteImport.update({
    id: '/onboarding-pending',
    path: '/onboarding-pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTimesheetRoute =
  AuthenticatedMyTimesheetRouteImport.update({
    id: '/my-timesheet',
    path: '/my-timesheet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteOnboardingRoute =
  AuthenticatedCompleteOnboardingRouteImport.update({
    id: '/complete-onboarding',
    path: '/complete-onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBdRoute = AuthenticatedBdRouteImport.update({
  id: '/bd',
  path: '/bd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBdIndexRoute = AuthenticatedBdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBdRoute,
} as any)
const ApiAssistantTranscribeRoute = ApiAssistantTranscribeRouteImport.update({
  id: '/api/assistant/transcribe',
  path: '/api/assistant/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantChatRoute = ApiAssistantChatRouteImport.update({
  id: '/api/assistant/chat',
  path: '/api/assistant/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHrOnboardingRoute =
  AuthenticatedHrOnboardingRouteImport.update({
    id: '/hr/onboarding',
    path: '/hr/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrLeaveRoute = AuthenticatedHrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardDeptRoute = AuthenticatedBoardDeptRouteImport.update({
  id: '/board/$dept',
  path: '/board/$dept',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBdTeamRoute = AuthenticatedBdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedBdRoute,
} as any)
const AuthenticatedBdReportsRoute = AuthenticatedBdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedBdRoute,
} as any)
const AuthenticatedBdRecurringRoute =
  AuthenticatedBdRecurringRouteImport.update({
    id: '/recurring',
    path: '/recurring',
    getParentRoute: () => AuthenticatedBdRoute,
  } as any)
const AuthenticatedBdActivityTypesRoute =
  AuthenticatedBdActivityTypesRouteImport.update({
    id: '/activity-types',
    path: '/activity-types',
    getParentRoute: () => AuthenticatedBdRoute,
  } as any)
const AuthenticatedAdminTaxonomyRoute =
  AuthenticatedAdminTaxonomyRouteImport.update({
    id: '/admin/taxonomy',
    path: '/admin/taxonomy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/google-calendar-connect': typeof GoogleCalendarConnectRoute
  '/access': typeof AuthenticatedAccessRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/bd': typeof AuthenticatedBdRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/complete-onboarding': typeof AuthenticatedCompleteOnboardingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/my-timesheet': typeof AuthenticatedMyTimesheetRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/onboarding-pending': typeof AuthenticatedOnboardingPendingRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/project-burn': typeof AuthenticatedProjectBurnRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/punch': typeof AuthenticatedPunchRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/timesheet': typeof AuthenticatedTimesheetRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/bd/activity-types': typeof AuthenticatedBdActivityTypesRoute
  '/bd/recurring': typeof AuthenticatedBdRecurringRoute
  '/bd/reports': typeof AuthenticatedBdReportsRoute
  '/bd/team': typeof AuthenticatedBdTeamRoute
  '/board/$dept': typeof AuthenticatedBoardDeptRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/onboarding': typeof AuthenticatedHrOnboardingRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/transcribe': typeof ApiAssistantTranscribeRoute
  '/bd/': typeof AuthenticatedBdIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/google-calendar-connect': typeof GoogleCalendarConnectRoute
  '/access': typeof AuthenticatedAccessRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/complete-onboarding': typeof AuthenticatedCompleteOnboardingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/my-timesheet': typeof AuthenticatedMyTimesheetRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/onboarding-pending': typeof AuthenticatedOnboardingPendingRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/project-burn': typeof AuthenticatedProjectBurnRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/punch': typeof AuthenticatedPunchRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/timesheet': typeof AuthenticatedTimesheetRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/bd/activity-types': typeof AuthenticatedBdActivityTypesRoute
  '/bd/recurring': typeof AuthenticatedBdRecurringRoute
  '/bd/reports': typeof AuthenticatedBdReportsRoute
  '/bd/team': typeof AuthenticatedBdTeamRoute
  '/board/$dept': typeof AuthenticatedBoardDeptRoute
  '/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/hr/onboarding': typeof AuthenticatedHrOnboardingRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/transcribe': typeof ApiAssistantTranscribeRoute
  '/bd': typeof AuthenticatedBdIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/google-calendar-connect': typeof GoogleCalendarConnectRoute
  '/_authenticated/access': typeof AuthenticatedAccessRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/bd': typeof AuthenticatedBdRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/complete-onboarding': typeof AuthenticatedCompleteOnboardingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/my-timesheet': typeof AuthenticatedMyTimesheetRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/onboarding-pending': typeof AuthenticatedOnboardingPendingRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/project-burn': typeof AuthenticatedProjectBurnRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/punch': typeof AuthenticatedPunchRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/timesheet': typeof AuthenticatedTimesheetRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/_authenticated/bd/activity-types': typeof AuthenticatedBdActivityTypesRoute
  '/_authenticated/bd/recurring': typeof AuthenticatedBdRecurringRoute
  '/_authenticated/bd/reports': typeof AuthenticatedBdReportsRoute
  '/_authenticated/bd/team': typeof AuthenticatedBdTeamRoute
  '/_authenticated/board/$dept': typeof AuthenticatedBoardDeptRoute
  '/_authenticated/hr/leave': typeof AuthenticatedHrLeaveRoute
  '/_authenticated/hr/onboarding': typeof AuthenticatedHrOnboardingRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/assistant/transcribe': typeof ApiAssistantTranscribeRoute
  '/_authenticated/bd/': typeof AuthenticatedBdIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/google-calendar-connect'
    | '/access'
    | '/attendance'
    | '/bd'
    | '/calendar'
    | '/complete-onboarding'
    | '/dashboard'
    | '/directory'
    | '/finances'
    | '/leave'
    | '/meetings'
    | '/my-timesheet'
    | '/onboarding'
    | '/onboarding-pending'
    | '/performance'
    | '/project-burn'
    | '/projects'
    | '/punch'
    | '/resources'
    | '/tasks'
    | '/team'
    | '/timesheet'
    | '/vendors'
    | '/workflows'
    | '/auth/callback'
    | '/admin/taxonomy'
    | '/bd/activity-types'
    | '/bd/recurring'
    | '/bd/reports'
    | '/bd/team'
    | '/board/$dept'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/api/assistant/chat'
    | '/api/assistant/transcribe'
    | '/bd/'
    | '/api/public/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/google-calendar-connect'
    | '/access'
    | '/attendance'
    | '/calendar'
    | '/complete-onboarding'
    | '/dashboard'
    | '/directory'
    | '/finances'
    | '/leave'
    | '/meetings'
    | '/my-timesheet'
    | '/onboarding'
    | '/onboarding-pending'
    | '/performance'
    | '/project-burn'
    | '/projects'
    | '/punch'
    | '/resources'
    | '/tasks'
    | '/team'
    | '/timesheet'
    | '/vendors'
    | '/workflows'
    | '/auth/callback'
    | '/admin/taxonomy'
    | '/bd/activity-types'
    | '/bd/recurring'
    | '/bd/reports'
    | '/bd/team'
    | '/board/$dept'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/api/assistant/chat'
    | '/api/assistant/transcribe'
    | '/bd'
    | '/api/public/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/google-calendar-connect'
    | '/_authenticated/access'
    | '/_authenticated/attendance'
    | '/_authenticated/bd'
    | '/_authenticated/calendar'
    | '/_authenticated/complete-onboarding'
    | '/_authenticated/dashboard'
    | '/_authenticated/directory'
    | '/_authenticated/finances'
    | '/_authenticated/leave'
    | '/_authenticated/meetings'
    | '/_authenticated/my-timesheet'
    | '/_authenticated/onboarding'
    | '/_authenticated/onboarding-pending'
    | '/_authenticated/performance'
    | '/_authenticated/project-burn'
    | '/_authenticated/projects'
    | '/_authenticated/punch'
    | '/_authenticated/resources'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/_authenticated/timesheet'
    | '/_authenticated/vendors'
    | '/_authenticated/workflows'
    | '/auth/callback'
    | '/_authenticated/admin/taxonomy'
    | '/_authenticated/bd/activity-types'
    | '/_authenticated/bd/recurring'
    | '/_authenticated/bd/reports'
    | '/_authenticated/bd/team'
    | '/_authenticated/board/$dept'
    | '/_authenticated/hr/leave'
    | '/_authenticated/hr/onboarding'
    | '/api/assistant/chat'
    | '/api/assistant/transcribe'
    | '/_authenticated/bd/'
    | '/api/public/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  GoogleCalendarConnectRoute: typeof GoogleCalendarConnectRoute
  ApiAssistantChatRoute: typeof ApiAssistantChatRoute
  ApiAssistantTranscribeRoute: typeof ApiAssistantTranscribeRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/google-calendar-connect': {
      id: '/google-calendar-connect'
      path: '/google-calendar-connect'
      fullPath: '/google-calendar-connect'
      preLoaderRoute: typeof GoogleCalendarConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timesheet': {
      id: '/_authenticated/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof AuthenticatedTimesheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/punch': {
      id: '/_authenticated/punch'
      path: '/punch'
      fullPath: '/punch'
      preLoaderRoute: typeof AuthenticatedPunchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-burn': {
      id: '/_authenticated/project-burn'
      path: '/project-burn'
      fullPath: '/project-burn'
      preLoaderRoute: typeof AuthenticatedProjectBurnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding-pending': {
      id: '/_authenticated/onboarding-pending'
      path: '/onboarding-pending'
      fullPath: '/onboarding-pending'
      preLoaderRoute: typeof AuthenticatedOnboardingPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-timesheet': {
      id: '/_authenticated/my-timesheet'
      path: '/my-timesheet'
      fullPath: '/my-timesheet'
      preLoaderRoute: typeof AuthenticatedMyTimesheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-onboarding': {
      id: '/_authenticated/complete-onboarding'
      path: '/complete-onboarding'
      fullPath: '/complete-onboarding'
      preLoaderRoute: typeof AuthenticatedCompleteOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bd': {
      id: '/_authenticated/bd'
      path: '/bd'
      fullPath: '/bd'
      preLoaderRoute: typeof AuthenticatedBdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access': {
      id: '/_authenticated/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthenticatedAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bd/': {
      id: '/_authenticated/bd/'
      path: '/'
      fullPath: '/bd/'
      preLoaderRoute: typeof AuthenticatedBdIndexRouteImport
      parentRoute: typeof AuthenticatedBdRoute
    }
    '/api/assistant/transcribe': {
      id: '/api/assistant/transcribe'
      path: '/api/assistant/transcribe'
      fullPath: '/api/assistant/transcribe'
      preLoaderRoute: typeof ApiAssistantTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/chat': {
      id: '/api/assistant/chat'
      path: '/api/assistant/chat'
      fullPath: '/api/assistant/chat'
      preLoaderRoute: typeof ApiAssistantChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hr/onboarding': {
      id: '/_authenticated/hr/onboarding'
      path: '/hr/onboarding'
      fullPath: '/hr/onboarding'
      preLoaderRoute: typeof AuthenticatedHrOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/leave': {
      id: '/_authenticated/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AuthenticatedHrLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board/$dept': {
      id: '/_authenticated/board/$dept'
      path: '/board/$dept'
      fullPath: '/board/$dept'
      preLoaderRoute: typeof AuthenticatedBoardDeptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bd/team': {
      id: '/_authenticated/bd/team'
      path: '/team'
      fullPath: '/bd/team'
      preLoaderRoute: typeof AuthenticatedBdTeamRouteImport
      parentRoute: typeof AuthenticatedBdRoute
    }
    '/_authenticated/bd/reports': {
      id: '/_authenticated/bd/reports'
      path: '/reports'
      fullPath: '/bd/reports'
      preLoaderRoute: typeof AuthenticatedBdReportsRouteImport
      parentRoute: typeof AuthenticatedBdRoute
    }
    '/_authenticated/bd/recurring': {
      id: '/_authenticated/bd/recurring'
      path: '/recurring'
      fullPath: '/bd/recurring'
      preLoaderRoute: typeof AuthenticatedBdRecurringRouteImport
      parentRoute: typeof AuthenticatedBdRoute
    }
    '/_authenticated/bd/activity-types': {
      id: '/_authenticated/bd/activity-types'
      path: '/activity-types'
      fullPath: '/bd/activity-types'
      preLoaderRoute: typeof AuthenticatedBdActivityTypesRouteImport
      parentRoute: typeof AuthenticatedBdRoute
    }
    '/_authenticated/admin/taxonomy': {
      id: '/_authenticated/admin/taxonomy'
      path: '/admin/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBdRouteChildren {
  AuthenticatedBdActivityTypesRoute: typeof AuthenticatedBdActivityTypesRoute
  AuthenticatedBdRecurringRoute: typeof AuthenticatedBdRecurringRoute
  AuthenticatedBdReportsRoute: typeof AuthenticatedBdReportsRoute
  AuthenticatedBdTeamRoute: typeof AuthenticatedBdTeamRoute
  AuthenticatedBdIndexRoute: typeof AuthenticatedBdIndexRoute
}

const AuthenticatedBdRouteChildren: AuthenticatedBdRouteChildren = {
  AuthenticatedBdActivityTypesRoute: AuthenticatedBdActivityTypesRoute,
  AuthenticatedBdRecurringRoute: AuthenticatedBdRecurringRoute,
  AuthenticatedBdReportsRoute: AuthenticatedBdReportsRoute,
  AuthenticatedBdTeamRoute: AuthenticatedBdTeamRoute,
  AuthenticatedBdIndexRoute: AuthenticatedBdIndexRoute,
}

const AuthenticatedBdRouteWithChildren = AuthenticatedBdRoute._addFileChildren(
  AuthenticatedBdRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBdRoute: typeof AuthenticatedBdRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCompleteOnboardingRoute: typeof AuthenticatedCompleteOnboardingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedMyTimesheetRoute: typeof AuthenticatedMyTimesheetRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOnboardingPendingRoute: typeof AuthenticatedOnboardingPendingRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProjectBurnRoute: typeof AuthenticatedProjectBurnRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPunchRoute: typeof AuthenticatedPunchRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTimesheetRoute: typeof AuthenticatedTimesheetRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedAdminTaxonomyRoute: typeof AuthenticatedAdminTaxonomyRoute
  AuthenticatedBoardDeptRoute: typeof AuthenticatedBoardDeptRoute
  AuthenticatedHrLeaveRoute: typeof AuthenticatedHrLeaveRoute
  AuthenticatedHrOnboardingRoute: typeof AuthenticatedHrOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBdRoute: AuthenticatedBdRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCompleteOnboardingRoute: AuthenticatedCompleteOnboardingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedMyTimesheetRoute: AuthenticatedMyTimesheetRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOnboardingPendingRoute: AuthenticatedOnboardingPendingRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProjectBurnRoute: AuthenticatedProjectBurnRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPunchRoute: AuthenticatedPunchRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTimesheetRoute: AuthenticatedTimesheetRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedAdminTaxonomyRoute: AuthenticatedAdminTaxonomyRoute,
  AuthenticatedBoardDeptRoute: AuthenticatedBoardDeptRoute,
  AuthenticatedHrLeaveRoute: AuthenticatedHrLeaveRoute,
  AuthenticatedHrOnboardingRoute: AuthenticatedHrOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  GoogleCalendarConnectRoute: GoogleCalendarConnectRoute,
  ApiAssistantChatRoute: ApiAssistantChatRoute,
  ApiAssistantTranscribeRoute: ApiAssistantTranscribeRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
